# -*- coding: utf-8 -*-
"""DA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Enny7xLr3-d5d6ZVsy6nUho-VYfHPU4

<a href="https://colab.research.google.com/github/aditya-malte/Simple-LP1-Codes/blob/master/DA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Download the file and save as iris.csv.
"""

!curl https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data --output iris.csv

import pandas as pd

data = pd.read_csv("iris.csv", names=["sepal_length","sepal_width","petal_length","petal_width","class"])

data.dtypes

data.head()

data.describe()

data.hist()

data.boxplot()